[intro.greeting]
speaker = "graham"
text = "Hello there!"
options = [["Uhm... hi?", "intro.arrival"]]

[intro.arrival]
speaker = "graham"
text = "You must be the new arrival. Parker, right?"
options = [["Yes.", "intro.alex"], ["That's me.", "intro.alex"], ["I guess so.", "intro.alex"]]

[intro.alex]
speaker = "alex"
text = "And I am AL3X."
options = [["Ok.", "intro.greeting"]]
