##############################################################################
###                                                                        ###
###                            HERE BE SPOILERS                            ###
###                                                                        ###
##############################################################################
[spoilers]
spoilers = true

[intro.snow]
speaker = ""
tensity = 0
text = "The ground here is white and soft. My boots sink into it with each step. \n \n This is apparently the last remaining place on earth with snow. But boy is there a lot of it. \n I'll be glad when it's all gone."
options = [["", "intro.facility"]]

[intro.facility]
speaker = ""
text = "This must be it."
options = [["", "intro.walking"]]

[intro.walking]
speaker = ""
text = ""
options = [["", "intro.greeting"]]

[intro.greeting]
speaker = "graham"
speaker_is_new = true
text = "Hello there! \n You must be our new security officer. Parker, right?"
options = [["Yes.", "intro.im_graham"], ["That's me.", "intro.im_graham"], ["I guess so.", "intro.im_graham"]]

[intro.im_graham]
speaker = "graham"
text = "I'm Graham, nice to meet you. \n Come on, let's get you out of the cold."
options = [["", "intro.out_of_the_cold"]]

[intro.out_of_the_cold]
speaker = ""
text = ""
options = [["", "intro.approaching_alex"]]

[intro.approaching_alex]
speaker = ""
tensity = 0.5
text = ""
options = [["", "intro.intruder"]]

[intro.intruder]
speaker = "alex"
speaker_is_new = true
tensity = 0.7
text = "Intruder detected! Eliminating in 3..."
options = [["Uhm...", "intro.intruder2"]]

[intro.intruder2]
speaker = "alex"
tensity = 1
text = "2..."
options = [["", "intro.intruder1"],  ["Graham, some help here?", "intro.intruder1"], ["Don't shoot!", "intro.just_kidding"]]

[intro.intruder1]
speaker = "alex"
tensity = 1
text = "1..."
options = [["", "intro.alex_shoots"], ["Don't shoot!", "intro.just_kidding"], ["Do it. End me.", "intro.thats_dark"]]

[intro.alex_shoots]
speaker = "alex"
tensity = 1
text = "BANG!"
options = [["", "intro.just_kidding"]]

[intro.thats_dark]
speaker = "alex"
tensity = 0.5
text = "Woah, that's dark. \n I was just messing with you."
options = [["And who are you?", "intro.im_alex"]]

[intro.just_kidding]
speaker = "alex"
text = "Just kidding."
tensity = 0.5
options = [["Not funny.", "intro.dont_mind"], ["Good one.", "intro.dont_mind"], ["What are you, a comedy robot?", "intro.im_alex"]]

[intro.dont_mind]
speaker = "graham"
tensity = 0.4
text = "Don't mind him, he's just excited to see a new face."
options = [["He?", "intro.im_alex"]]

[intro.im_alex]
speaker = "alex"
tensity = 0.2
text = "I am AL3X, the Artificial Living, Learning and Locating Exterminator. \n Most people here call me Alex."
options = [["Nice to meet you, Alex.", "intro.dont_worry"], ["That sounds dangerous.", "intro.dont_worry"]]

[intro.dont_worry]
speaker = "alex"
tensity = 0
text = "Don't worry, my programming forbids me from harming humans. I've never killed anything larger than a rat."
options = [["That's comforting.", "intro.tired"], ["Are there rats in Antarctica?", "intro.no_rats"]]

[intro.no_rats]
speaker = "alex"
text = "Not anymore!"
options = [["Right.", "intro.tired"]]

[intro.tired]
speaker = "graham"
text = "You must be tired. \n Alex will show you to your room. We'll talk shop in the morning."
options = [["I'm exhausted.", "intro.one_last_thing"], ["Sounds good.", "intro.one_last_thing"]]

[intro.one_last_thing]
speaker = "graham"
text = "Oh, one last thing. \n Here's a portable computer. It should contain all the files you need."
options = [["!TAKE THE DEVICE", "intro.goodnight"]]

[intro.goodnight]
speaker = "graham"
text = "Good night!"
flags = ["pc_online"]
options = [["Good night.", "intro.following_alex"]]

[intro.following_alex]
speaker = ""
text = ""
options = [["", "intro.follow_me"]]

[intro.follow_me]
speaker = "alex"
text = "Ok, follow me. Our rooms are opposite each other. Isn't that funny?"
options = [["Yeah.", "intro.trick"], ["Is it?", "intro.guess_not"], ["You have a bedroom?", "intro.about_bedroom"]]

[intro.trick]
speaker = "alex"
text = "Here we are."
options = [["!OPEN THE DOOR", "intro.live_laugh_learn"]]

[intro.guess_not]
speaker = "alex"
text = "I guess not."
flags = ["alex_sad"]
options = [["", "intro.on_the_right"]]

[intro.on_the_right]
speaker = "alex"
text = "Your room is the one on the right."
options = [["!OPEN THE DOOR", "intro.leave_you"]]

[intro.about_bedroom]
speaker = "alex"
text = "Yeah, so to speak. It doesn't have a bed, but I recharge there a few hours each night. \n Do you want to see it?"
options = [["Sure.", "intro.live_laugh_learn"], ["Not really.", "intro.nevermind"]]

[intro.nevermind]
speaker = "alex"
text = "Nevermind."
flags = ["alex_sad"]
options = [["", "intro.other_door"]]

[intro.live_laugh_learn]
speaker = ""
text = ""
flags = ["alex_happy"]
options = [["", "intro.other_door"]]

[intro.other_door]
speaker = "alex"
text = "Your room is the one on the right."
options = [["!OPEN THE OTHER DOOR", "intro.leave_you"]]

[intro.leave_you]
speaker = "alex"
text = "I'll leave you to it, then."
options = [["Thanks. Good night.", "intro.sleep_tight"], ["!SHUT THE DOOR", "intro.sleep"]]

[intro.sleep_tight]
speaker = "alex"
text = "Sleep tight."
flags = ["alex_happy"]
options = [["!CLOSE THE DOOR", "intro.sleep"]]

[intro.sleep]
speaker = ""
text = ""
flags = ["pc_offline"]
options = [["!GO TO SLEEP", "day2.wake_up"]]

[day2.wake_up]
speaker = ""
tensity = 0
text = "I wake up from a restless night. \n It's so cold, I feel like I barely slept. \n I get up and make my way to the canteen."
options = [["", "day2.canteen"]]

[day2.canteen]
speaker = ""
text = "The food doesn't look very appetizing, so I walk up to a table where three people are seated."
options = [["", "day2.hazel"]]

[day2.hazel]
speaker = "hazel"
speaker_is_new = true
text = "Hi there stranger! \n Rough night?"
options = [["You could say that.", "day2.first_night"], ["I slept fine.", "day2.unusual"]]

[day2.first_night]
speaker = "hazel"
text = "All of us had trouble sleeping on our first night. \n I think it's the silence. No cars, no jam ads. It freaks people out. \n Did you know that 50 years ago there were no jam ads? Hadn't been invented yet. \n Crazy, right? \n Of course back then there were mosquitoes buzzing all night and birds chirping all day. \n Luckily we got rid of those. \n I'm Hazel by the way."
options = [["Right.", "day2.rude"], ["I'm Parker.", "day2.nice"]]

[day2.unusual]
speaker = "hazel"
text = "Huh, lucky you. \n I'm Hazel. And this is Rory, and Bill."
flags = ["human_suspicious"]
options = [["", "day2.rory"]]

[day2.rude]
speaker = "hazel"
text = "... \n Oh, this is Rory, and Bill."
flags = ["human_sad"]
options = [["", "day2.rory"]]

[day2.nice]
speaker = "hazel"
text = "And this is Rory, and Bill."
flags = ["human_happy"]
options = [["", "day2.rory"]]

[day2.rory]
speaker = "rory"
speaker_is_new = true
text = "Howdy!"
options = [["", "day2.bill"]]

[day2.bill]
speaker = "bill"
speaker_is_new = true
text = "Good morning."
options = [["", "day2.want_to_stay"]]

[day2.want_to_stay]
speaker = "hazel"
text = "Sit down, tell us a little about yourself."
options = [["!SIT DOWN", "day2.stay"], ["I have work to do.", "day2.leave"]]

[day2.leave]
speaker = "hazel"
text = "Oh, of course you do."
flags = ["human_sad"]
options = [["Where can I find Graham?", "day2.where_graham"]]

[day2.stay]
speaker = "hazel"
text = "So you're our new security officer, right? \n Makes sense that they hire someone, what with the big discovery and all the secrecy around it."
flags = ["human_happy"]
options = [["What discovery?", "day2.what_discovery"]]

[day2.what_discovery]
speaker = "hazel"
text = "The micro-organisms in the..."
flags = ["unknown_micro_organisms"]
options = [["", "day2.shush"]]

[day2.shush]
speaker = "rory"
text = "Hazel! \n Sorry hoss, we were instructed not to tell you unless you already know."
options = [["", "to_be_continued"]]



[day2.where_graham]
speaker = "rory"
text = "Oh, he's around somewhere."
options = [["I'll go look for him.", "to_be_continued"]]



[to_be_continued]
speaker = ""
text = "TO BE CONTINUED"
options = [["", "the_end"]]

[the_end]
speaker = ""
tensity = 0
text = "THE END"
options = [["!REPLAY FROM START", "intro.snow"]]
